version: '3.8'

services:
  web:
    build: .
    container_name: patent_web_service
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  tests:
    build: .
    container_name: patent_service_tests
    env_file:
      - .env
    volumes:
      - .:/app
    command: pytest --cov=src --cov-report=xml --cov-report=term-missing tests/
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
