name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create env file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
        echo "ROSPATENT_JWT=${{ secrets.ROSPATENT_JWT }}" >> .env
        echo "GIGACHAT_CLIENT_ID=${{ secrets.GIGACHAT_CLIENT_ID }}" >> .env
        echo "GIGACHAT_CLIENT_SECRET=${{ secrets.GIGACHAT_CLIENT_SECRET }}" >> .env
        echo "LOG_LEVEL=DEBUG" >> .env

    - name: Build Docker images
      run: docker compose build --no-cache
